In [6]:
import numpy as np
a=np.zeros(10)

#### 2. Create a null vector of size 10 (★☆☆)

In [7]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (

In [8]:
a[4]=1

In [9]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (

In [18]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix 

In [20]:
np.eye(3, k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [36]:
a = np.random.random((3,3,3))
a

array([[[0.42931528, 0.88605679, 0.70888468],
        [0.27000237, 0.73663013, 0.93890647],
        [0.51666385, 0.17778501, 0.64880046]],

       [[0.92659534, 0.33311824, 0.03892817],
        [0.49985034, 0.02262711, 0.29793508],
        [0.63351431, 0.84826662, 0.7454109 ]],

       [[0.32316427, 0.69131192, 0.69526689],
        [0.36201473, 0.21622315, 0.15075867],
        [0.93552899, 0.90244006, 0.83837652]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [78]:
a = np.random.random((10,10))
np.max(a)


0.9943723444077136

In [44]:
np.min(a)


0.013909533182808964

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [47]:
x = np.random.random(30)
x

array([0.51177077, 0.93826793, 0.27618284, 0.79644647, 0.54126614,
       0.6505894 , 0.57618005, 0.17879709, 0.45340803, 0.05085625,
       0.87226501, 0.67908734, 0.88674694, 0.46552787, 0.66355561,
       0.62254299, 0.93406447, 0.64262541, 0.83238486, 0.45739789,
       0.91010813, 0.66362886, 0.91571984, 0.35118802, 0.38825398,
       0.3842296 , 0.47178587, 0.59378889, 0.35165238, 0.76937825])

In [48]:
np.mean(x)

0.5943232387701504

**11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [193]:
x = np.random.random((5,5))
x[range(1,5),range(4)]=1,2,3,4
x

array([[0.44134023, 0.93323657, 0.0297937 , 0.23168769, 0.47995396],
       [1.        , 0.08321101, 0.22663524, 0.09185562, 0.66999071],
       [0.01954596, 2.        , 0.43706684, 0.59635316, 0.58083366],
       [0.04867481, 0.95102835, 3.        , 0.05819683, 0.54812112],
       [0.3503207 , 0.87805347, 0.00870648, 4.        , 0.61787502]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std`

In [73]:
x = np.random.random((5,5))
(x-np.mean(x))/np.std(x)

array([[-0.8419372 , -0.65467754, -0.21974518, -1.61398038, -1.0946556 ],
       [-0.92757159,  1.34050636,  1.56324112, -0.43680231,  0.6444085 ],
       [-0.15113634,  1.71377939,  0.19239522, -0.9862622 ,  0.14507743],
       [ 1.55137966, -1.13954145, -0.51358587,  0.8174973 , -1.07744179],
       [ 0.18636817,  1.04080109, -1.14578772,  0.17461284,  1.43305809]])

#### 13. How to find common values between two arrays?

In [74]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

#### 14. Create a random vector of size 10 and sort it (★★☆)

In [76]:
x = np.random.random(10)
np.sort(x)

array([0.13844315, 0.23617371, 0.4455779 , 0.46005611, 0.46793338,
       0.65113269, 0.81206223, 0.81302827, 0.82074461, 0.91983792])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [87]:
x = np.random.random(10)
x[np.where(x == max(x))]=0
x

array([0.2432889 , 0.20141698, 0.78392603, 0.15450236, 0.17270381,
       0.42090019, 0.        , 0.28206293, 0.16354751, 0.89814859])

#### 16. Subtract the mean of each row of a matrix (★★☆)
mean(axis=,keepdims=)

In [94]:
x = np.random.random((5,4))
x


array([[0.53360823, 0.90371655, 0.30535782, 0.02172624],
       [0.15789003, 0.79973642, 0.21147614, 0.58609173],
       [0.0437431 , 0.13217953, 0.60562793, 0.50110614],
       [0.25566102, 0.70369532, 0.52792935, 0.03062403],
       [0.30336264, 0.25079989, 0.68122055, 0.23398639]])

In [132]:
np.mean(x,axis=1,keepdims=True)

array([[0.44110221],
       [0.43879858],
       [0.32066418],
       [0.37947743],
       [0.36734237]])

In [133]:
y=x-np.mean(x,axis=1,keepdims=True)


In [134]:
y

array([[ 0.09250602,  0.46261434, -0.13574439, -0.41937597],
       [-0.28090855,  0.36093784, -0.22732244,  0.14729315],
       [-0.27692107, -0.18848465,  0.28496376,  0.18044196],
       [-0.12381641,  0.32421789,  0.14845192, -0.3488534 ],
       [-0.06397972, -0.11654248,  0.31387818, -0.13335598]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`


In [147]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5



In [148]:
z

array([6521, 2432, 6615, ..., 4346, 4134, 2387])

In [156]:
r=np.sort(z)

In [157]:
r

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [221]:
r[np.argsort(r)[-n:]]

array([9995, 9996, 9997, 9998, 9999])

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [232]:
z = np.arange(16)
np.random.shuffle(z)
a=z.reshape(5,3)

ValueError: cannot reshape array of size 16 into shape (5,3)

In [267]:
x=np.random.randint(16, size=(5, 3))
x


array([[ 6, 15,  8],
       [ 2,  3,  4],
       [13, 11,  3],
       [ 8,  5,  5],
       [ 2,  2,  6]])

In [254]:
for i in np.nditer(x):
    if i > 4:
        i=i**2



array([[ 1,  3,  0],
       [ 1,  4,  7],
       [15, 10, 13],
       [ 6, 15,  2],
       [ 4,  5, 12]])

In [264]:
y=x[np.where(x > 4)]
for i in x:
    x[y]=x**2
    

ValueError: shape mismatch: value array of shape (5,3) could not be broadcast to indexing result of shape (8,3)